#!/bin/bash
check_ruby() {
  local RUBY="$1"
  if [ -n "$RUBY" ] && [ "$("$RUBY" -e "puts RUBY_VERSION.split('.')[0]")" = "2" ]
  then
    HOMEBREW_BUNDLE_RUBY="$RUBY"
  else
    false
  fi
}

if ! check_ruby "$HOMEBREW_RUBY_PATH" && ! check_ruby "ruby"
then
  echo "Ruby 2.0 or above is required. You can install it with `brew install ruby`." >&2
  exit 1
fi

COMMAND="$(basename "${BASH_SOURCE[0]}" | tr "-" " ")"
if [ "$COMMAND" != "brew bundle" ]
then
  echo "Warning: the '$COMMAND' command has been renamed to 'brew bundle'." >&2
fi

BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec "$HOMEBREW_BUNDLE_RUBY" "$BASE_PATH/cmd/brew-bundle.rb" $@
